version: "3.7"

services: 
 nostdress:
    build: . 
    container_name: nostdress
    environment:
      - PORT=17422
      - DOMAIN=example.com
      - DB_DIR=/data
      - SECRET=CHANGE_ME_NOW
      - SITE_OWNER_URL=https://example.com
      - SITE_OWNER_NAME=@me
      - SITE_NAME=Example.com
      - NOSTR_PRIVATE_KEY=<nsec....>
      - GET_NOSTR_PROFILE=false
      - RELAYS=wss://nostr.mutinywallet.com,wss://relay.nostrgraph.net,wss://blastr.f7z.xyz,wss://relay.damus.io/,wss://relay.utxo.one,wss://eden.nostr.land,wss://nostr.btcmp.com,wss://nostr.relayer.se,wss://relay.current.fyi,wss://nos.lol,wss://nostr.mom,wss://nostr.zebedee.cloud,wss://nostr-pub.wellorder.net,wss://relay.snort.social/,wss://nostr.oxtr.dev/,wss://nostr.fmt.wiz.biz/,wss://brb.io
    ports:
      - 17422:17422
    volumes:
      - ./data:/data
